### PR TITLE
Create embedHeader.js

### PR DESCRIPTION
**Pull request by DimensionalFusion**
why am I doing this

### CODE REVIEW

**Comment by imskyyc** [comment]
What is this looking to accomplish exactly?

**Comment by DimensionalFusion** [comment]
1) i made this on mobile
2) author embeds allow for links, so they’re more customisable
3) pbstFusion

**Comment by DimensionalFusion** [comment]
bruh!!!

**Comment by DimensionalFusion** [comment]
why not have it

**Comment by imskyyc** [comment]
There's no practical use for it. All of the commands would have to be changed to use it, and there's zero benefit.

**Comment by DimensionalFusion** [comment]
1) so I will change them all to use it
2) embedFooter exists, why not header
3) the benefit is that it allows for links, unlike footer embeds
4) I will be back soon with a revised version

**Pull request closed without merging**
